version: "3"

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=jobboard_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "./wait_db.sh db:5432 -- python main.py"
    env_file:
      - .env
    depends_on:
      - db